# Generated by Django 5.1.1 on 2024-11-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
        ('user', '0002_alter_buildings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authns',
            name='student_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='authns',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_info', to='user.users'),
        ),
    ]
