# Generated by Django 5.1.1 on 2024-10-29 18:12

import authn.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_authns_last_login_alter_authns_user_id'),
        ('user', '0002_rename_visuabliity_users_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authns',
            name='last_login',
        ),
        migrations.AddField(
            model_name='authns',
            name='role',
            field=models.CharField(choices=[(authn.models.RoleEnum['NORMAL'], 'NORMAL'), (authn.models.RoleEnum['ADMIN'], 'ADMIN')], default=authn.models.RoleEnum['NORMAL'], max_length=50),
        ),
        migrations.AlterField(
            model_name='authns',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_info', to='user.users'),
        ),
    ]
