# Generated by Django 5.1.1 on 2024-11-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_alter_authns_student_number_alter_authns_user_id'),
        ('user', '0002_alter_buildings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authns',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authn_info', to='user.users'),
        ),
    ]
