# Generated by Django 5.1.1 on 2024-10-29 18:14

import authn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0003_remove_authns_last_login_authns_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authns',
            name='role',
            field=models.CharField(choices=[(authn.models.RoleEnum['NORMAL'], 'NORMAL'), (authn.models.RoleEnum['ADMIN'], 'ADMIN')], default='NORMAL', max_length=50),
        ),
    ]
