# Generated by Django 5.1.1 on 2024-11-09 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0004_alter_authns_role'),
        ('user', '0005_rename_is_visuable_users_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authns',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='user.users'),
        ),
    ]
