# Generated by Django 5.1.1 on 2025-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buildings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('가온관', '가온관'), ('건축관', '건축관'), ('공학1관', '공학1관'), ('공학2관', '공학2관'), ('디자인관', '디자인관'), ('나래관', '나래관'), ('누리관', '누리관'), ('수산과학관', '수산과학관'), ('웅비관', '웅비관'), ('인문사회경영관', '인문사회경영관'), ('자연과학1관', '자연과학1관'), ('자연과학2관', '자연과학2관'), ('장영실관', '장영실관'), ('창의관', '창의관'), ('충무관', '충무관'), ('향파관', '향파관'), ('환경해양관', '환경해양관'), ('호연관', '호연관')], max_length=20)),
                ('floor', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
