# Generated by Django 5.1.1 on 2024-10-05 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabinets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='cabinet_histories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('cabinet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinets')),
            ],
        ),
    ]
