# Generated by Django 5.1.1 on 2024-11-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabinets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cabinet_number', models.IntegerField()),
                ('status', models.CharField(choices=[('BROKEN', 'BROKEN'), ('AVAILABLE', 'AVAILABLE'), ('USING', 'USING'), ('OVERDUE', 'OVERDUE')], default='AVAILABLE', max_length=20)),
                ('payable', models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='FREE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.buildings')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='cabinet_positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_x_pos', models.IntegerField()),
                ('cabinet_y_pos', models.IntegerField()),
                ('cabinet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinets')),
            ],
        ),
        migrations.CreateModel(
            name='cabinet_histories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('cabinet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinets')),
            ],
        ),
    ]
