# Generated by Django 5.1.1 on 2024-11-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('user', '0002_alter_users_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='building_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.buildings'),
        ),
        migrations.AlterField(
            model_name='cabinets',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.users'),
        ),
    ]
