# Generated by Django 5.1.1 on 2024-11-03 07:49

import cabinet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('user', '0003_rename_visibility_users_is_visuable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[(cabinet.models.BuildingNameEnum['가온관'], '가온관'), (cabinet.models.BuildingNameEnum['공학1관'], '공학1관'), (cabinet.models.BuildingNameEnum['공학2관'], '공학2관'), (cabinet.models.BuildingNameEnum['디자인관'], '디자인관'), (cabinet.models.BuildingNameEnum['나래관'], '나래관'), (cabinet.models.BuildingNameEnum['누리관'], '누리관'), (cabinet.models.BuildingNameEnum['수산과학관'], '수산과학관'), (cabinet.models.BuildingNameEnum['웅비관'], '웅비관'), (cabinet.models.BuildingNameEnum['인문사회경영관'], '인문사회경영관'), (cabinet.models.BuildingNameEnum['자연과학1관'], '자연과학1관'), (cabinet.models.BuildingNameEnum['자연과학2관'], '자연과학2관'), (cabinet.models.BuildingNameEnum['장영실관'], '장영실관'), (cabinet.models.BuildingNameEnum['창의관'], '창의관'), (cabinet.models.BuildingNameEnum['충무관'], '충무관'), (cabinet.models.BuildingNameEnum['향파관'], '향파관'), (cabinet.models.BuildingNameEnum['환경해양관'], '환경해양관'), (cabinet.models.BuildingNameEnum['호연관'], '호연관')], max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='building',
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='number',
        ),
        migrations.AddField(
            model_name='cabinets',
            name='payable',
            field=models.CharField(choices=[(cabinet.models.CabinetPayableEnum['PAID'], 'PAID'), (cabinet.models.CabinetPayableEnum['FREE'], 'FREE')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='cabinets',
            name='status',
            field=models.CharField(choices=[(cabinet.models.CabinetStatusEnum['BROKEN'], 'BROKEN'), (cabinet.models.CabinetStatusEnum['AVAILABLE'], 'AVAILABLE'), (cabinet.models.CabinetStatusEnum['OVERDUE'], 'OVERDUE')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cabinet_histories',
            name='cabinet_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinets'),
        ),
        migrations.AlterField(
            model_name='cabinet_histories',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
        migrations.AddField(
            model_name='cabinets',
            name='building_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.buildings'),
        ),
        migrations.CreateModel(
            name='cabinet_positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_x_pos', models.IntegerField()),
                ('cabinet_y_pos', models.IntegerField()),
                ('cabinet_number', models.IntegerField()),
                ('cabinet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinets')),
            ],
        ),
    ]
