# Generated by Django 5.1.1 on 2024-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='payable',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='FREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cabinets',
            name='status',
            field=models.CharField(choices=[('BROKEN', 'BROKEN'), ('AVAILABLE', 'AVAILABLE'), ('USING', 'USING'), ('OVERDUE', 'OVERDUE')], default='AVAILABLE', max_length=20),
        ),
    ]
