# Generated by Django 5.1.1 on 2024-11-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_buildings_remove_cabinets_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='building_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.buildings'),
        ),
    ]
