# Generated by Django 5.1.1 on 2025-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_cabinets_building_id_alter_cabinets_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinets',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
