# Generated by Django 5.1.1 on 2025-05-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_cabinet_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabinet_history_blockchains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_id', models.BigIntegerField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('blockchain_status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('network', models.CharField(default='ETHEREUM', max_length=20)),
                ('metadata_uri', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinet_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_record', to='cabinet.cabinet_histories')),
            ],
        ),
    ]
