# Generated by Django 5.1.1 on 2024-11-06 13:11

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_cabinets_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='status',
            field=models.CharField(choices=[(cabinet.models.CabinetStatusEnum['BROKEN'], 'BROKEN'), (cabinet.models.CabinetStatusEnum['AVAILABLE'], 'AVAILABLE'), (cabinet.models.CabinetStatusEnum['USING'], 'USING'), (cabinet.models.CabinetStatusEnum['OVERDUE'], 'OVERDUE')], default='AVAILABLE', max_length=20),
        ),
    ]
