# Generated by Django 5.1.1 on 2025-05-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_cabinet_history_blockchains'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cabinet_history_blockchains',
        ),
    ]
