# Generated by Django 5.1.1 on 2024-11-10 07:22

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buildings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[(user.models.BuildingNameEnum['가온관'], '가온관'), (user.models.BuildingNameEnum['공학1관'], '공학1관'), (user.models.BuildingNameEnum['공학2관'], '공학2관'), (user.models.BuildingNameEnum['디자인관'], '디자인관'), (user.models.BuildingNameEnum['나래관'], '나래관'), (user.models.BuildingNameEnum['누리관'], '누리관'), (user.models.BuildingNameEnum['수산과학관'], '수산과학관'), (user.models.BuildingNameEnum['웅비관'], '웅비관'), (user.models.BuildingNameEnum['인문사회경영관'], '인문사회경영관'), (user.models.BuildingNameEnum['자연과학1관'], '자연과학1관'), (user.models.BuildingNameEnum['자연과학2관'], '자연과학2관'), (user.models.BuildingNameEnum['장영실관'], '장영실관'), (user.models.BuildingNameEnum['창의관'], '창의관'), (user.models.BuildingNameEnum['충무관'], '충무관'), (user.models.BuildingNameEnum['향파관'], '향파관'), (user.models.BuildingNameEnum['환경해양관'], '환경해양관'), (user.models.BuildingNameEnum['호연관'], '호연관')], max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.buildings')),
            ],
        ),
    ]
