# Generated by Django 5.1.1 on 2025-03-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('cabinet', '0002_alter_cabinets_building_id_alter_cabinets_reason_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='building_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_info', to='building.buildings'),
        ),
        migrations.DeleteModel(
            name='buildings',
        ),
    ]
