# Generated by Django 5.1.1 on 2024-11-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='building',
            new_name='building_id',
        ),
    ]
