# Generated by Django 5.1.1 on 2024-10-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='visuabliity',
            new_name='visibility',
        ),
    ]
