# Generated by Django 5.1.1 on 2024-11-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_visuabliity_users_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='visibility',
            new_name='is_visuable',
        ),
        migrations.AddField(
            model_name='users',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
