# Generated by Django 5.1.1 on 2024-11-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='name',
            field=models.CharField(choices=[('가온관', '가온관'), ('건축관', '건축관'), ('공학1관', '공학1관'), ('공학2관', '공학2관'), ('디자인관', '디자인관'), ('나래관', '나래관'), ('누리관', '누리관'), ('수산과학관', '수산과학관'), ('웅비관', '웅비관'), ('인문사회경영관', '인문사회경영관'), ('자연과학1관', '자연과학1관'), ('자연과학2관', '자연과학2관'), ('장영실관', '장영실관'), ('창의관', '창의관'), ('충무관', '충무관'), ('향파관', '향파관'), ('환경해양관', '환경해양관'), ('호연관', '호연관')], max_length=20),
        ),
    ]
