# Generated by Django 5.1.1 on 2024-11-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_visibility_users_is_visuable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
