# Generated by Django 5.1.1 on 2024-11-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_visuable',
            new_name='is_visible',
        ),
    ]
